import type { Metadata } from "next";
import { Poppins, Quicksand } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["700"],
});

const quicksand = Quicksand({
  variable: "--font-base",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr">
      <body
        className={`${poppins.variable} ${quicksand.variable} flex min-h-screen flex-col overflow-x-hidden overflow-y-scroll antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
